### ISSUE TITLE
请问有没有办法跳过 Safari 对图片/实况文本的翻译啊？

### ISSUE THREAD

**Issue by suliveevil** [BlackwinMin/keyboard-maestro-gallery#2]
最近发现了您的 Safari Translate 如获至宝，感谢您的开发。

只是无论之前用鼠标点击还是现在用 Macro 都不能让 Safari 停止对图片/实况文本的翻译，请问有没有办法跳过 Safari 对图片/实况文本的翻译啊？谢谢 🙏

**Comment by BlackwinMin** [comment]
实况文本是系统级的功能，似乎只能完全关闭或完全开启（设置-通用-语言和地区-实况文本）。如果非常介意，可能要换个浏览器，当然，文章里的方法也适用于其他浏览器 :)

**Comment by suliveevil** [comment]
感谢😂我想想办法看能不能临时关闭它。

**Comment by BlackwinMin** [comment]
单独关闭可能暂时不行。不过，如果你的目的是剪藏网页，可以试试下面这篇文章的方法，打开阅读模式就可以让图片恢复原样
https://utgd.net/article/8492

**Comment by suliveevil** [comment]
感谢分享。
我主要是看社区的帖子，所以 Safari 的阅读模式体验很差 😂
