### ISSUE TITLE
windows的chrome或edge可以安装吗？

### ISSUE THREAD

**Issue by zhl111** [BlackwinMin/keyboard-maestro-gallery#3]
pc机没试出来

**Comment by suliveevil** [comment]
Keyboard Maestro 是 macOS 软件，不过有些思路和代码可以借鉴到 Windows 上。

**Comment by BlackwinMin** [comment]
文章中有 bookmarklet 版本，可以在 Windows 的主流浏览器上实现对照效果，并且已针对 Edge 等适用微软翻译 API 的浏览器进行优化；再配合浏览器本身的翻译功能，就能实现对照+翻译。
