### ISSUE TITLE
The macro "Thousands Separator" doesn't work for a number with more than 16 digits

### ISSUE THREAD

**Issue by rockyzhang24** [BlackwinMin/keyboard-maestro-gallery#5]
It works perfect for a number with 16 digits and less, but not for the one with more than 16 digits. For example, running the macro on a 17 digits number `11111111111111111` gets `11,111,111,111,111,112`. 

Thank you.

**Comment by BlackwinMin** [comment]
Due to the limitation of `toLocaleString` function, this macro cannot take into account the higher digits. There doesn't seem to be an existing function to do this, and using someone else's code has a legal risk, so I'll just accept the current version until I found a better one ;)

**Comment by rockyzhang24** [comment]
I see. Thank you. I was just wondering whether the corner case could be solved. Actually a number with so much digits is meaningless. I will close this issue.
